import 'package:tonic/tonic.dart';

Map harmonicMajorModes = {
  'Dorian ♭5': {
    'scaleStepsRoman': ['I', 'II', '♭III', 'IV', 'V', 'VI', '♭VII'],
    'triad': [Interval.P1, Interval.M2, Interval.m3],
    'tetrade': [Interval.P1, Interval.M2, Interval.m3, Interval.M6],
    'intervals': [0, 2, 3, 5, 7, 8, 10],
    'scaleDegrees': [
      Interval.P1,
      Interval.M2,
      Interval.m3,
      Interval.P4,
      Interval.P5,
      Interval.M6,
      Interval.m7,
    ],
    'function': ['I', 'ii', '♭III', 'IV', 'V', 'vi', '♭VII'],
    'chordType': ['m', 'm', '°', 'M', 'm', '°', '°'],
  },
  'Phrygian ♭4': {
    'scaleStepsRoman': ['I', '♭II', '♭III', 'IV', 'V', 'VI', '♭VII'],
    'triad': [Interval.P1, Interval.m2, Interval.m3],
    'tetrade': [Interval.P1, Interval.m2, Interval.m3, Interval.P5],
    'intervals': [0, 1, 3, 5, 7, 8, 10],
    'scaleDegrees': [
      Interval.P1,
      Interval.m2,
      Interval.m3,
      Interval.P4,
      Interval.P5,
      Interval.M6,
      Interval.m7,
    ],
    'function': ['I', '♭ii', '♭III', 'IV', 'V', 'vi', '♭VII'],
    'chordType': ['m', '°', 'm', 'M', 'm', '°', '°'],
  },
  'Lydian ♯3': {
    'scaleStepsRoman': ['I', 'II', '♭III', '♯IV', 'V', 'VI', 'VII'],
    'triad': [Interval.P1, Interval.M2, Interval.m3],
    'tetrade': [Interval.P1, Interval.M2, Interval.m3, Interval.M6],
    'intervals': [0, 2, 3, 6, 7, 9, 11],
    'scaleDegrees': [
      Interval.P1,
      Interval.M2,
      Interval.m3,
      Interval.A4,
      Interval.P5,
      Interval.M6,
      Interval.M7,
    ],
    'function': ['I', 'ii', '♭III', '♯IV', 'V', 'vi', 'vii'],
    'chordType': ['m', 'm', '°', '+', 'M', '°', '°'],
  },
  'Lydian ♯2': {
    'scaleStepsRoman': ['I', '♯II', '♯III', 'IV', 'V', 'VI', 'VII'],
    'triad': [Interval.P1, Interval.A2, Interval.A3],
    'tetrade': [Interval.P1, Interval.A2, Interval.A3, Interval.M6],
    'intervals': [0, 3, 4, 5, 7, 8, 10],
    'scaleDegrees': [
      Interval.P1,
      Interval.A2,
      Interval.A3,
      Interval.P4,
      Interval.P5,
      Interval.M6,
      Interval.m7,
    ],
    'function': ['I', '♯II', '♯III', 'IV', 'V', 'vi', '♭VII'],
    'chordType': ['M', '+', 'm', 'M', 'M', '°', 'm'],
  },
  'Mixolydian ♯1': {
    'scaleStepsRoman': ['I', 'II', '♭III', 'IV', 'V', 'VI', 'VII'],
    'triad': [Interval.P1, Interval.M2, Interval.M3],
    'tetrade': [Interval.P1, Interval.M2, Interval.M3, Interval.P5],
    'intervals': [0, 2, 3, 5, 7, 8, 10],
    'scaleDegrees': [
      Interval.P1,
      Interval.M2,
      Interval.m3,
      Interval.P4,
      Interval.P5,
      Interval.M6,
      Interval.m7,
    ],
    'function': ['I', 'ii', '♭III', 'IV', 'V', 'vi', 'VII'],
    'chordType': ['M', 'm', '°', 'M', 'm', '°', 'm'],
  },
  'Aeolian ♯7': {
    'scaleStepsRoman': ['I', 'II', '♭III', 'IV', 'V', 'VI', '♯VII'],
    'triad': [Interval.P1, Interval.M2, Interval.m3],
    'tetrade': [Interval.P1, Interval.M2, Interval.m3, Interval.M6],
    'intervals': [0, 2, 3, 5, 7, 8, 11],
    'scaleDegrees': [
      Interval.P1,
      Interval.M2,
      Interval.m3,
      Interval.P4,
      Interval.P5,
      Interval.M6,
      Interval.M7,
    ],
    'function': ['I', 'ii', '♭III', 'IV', 'V', 'vi', '♯VII'],
    'chordType': ['m', 'm', '°', 'M', 'm', '°', '°'],
  },
  'Locrian ♭6': {
    'scaleStepsRoman': ['I', '♭II', '♭III', 'IV', 'V', '♭VI', '♭VII'],
    'triad': [Interval.P1, Interval.m2, Interval.m3],
    'tetrade': [Interval.P1, Interval.m2, Interval.m3, Interval.M6],
    'intervals': [0, 1, 3, 5, 7, 8, 10],
    'scaleDegrees': [
      Interval.P1,
      Interval.m2,
      Interval.m3,
      Interval.P4,
      Interval.P5,
      Interval.m6,
      Interval.m7,
    ],
    'function': ['I', '♭ii', '♭III', 'IV', 'V', '♭VI', '♭VII'],
    'chordType': ['°', 'm', '°', 'm', '°', '°', '°'],
  },
};
