import 'package:tonic/tonic.dart';

Map pentatonics = {
  'Major Pentatonic': {
    'scaleStepsRoman': ['I', 'II', 'III', 'V', 'VI'],
    'intervals': [0, 2, 4, 7, 9],
    'scaleDegrees': [
      Interval.P1,
      null,
      Interval.M2,
      null,
      Interval.M3,
      null,
      null,
      Interval.P5,
      null,
      Interval.M6,
      null,
    ],
    'function': ['I', 'II', 'III', 'V', 'VI'],
    'chordType': ['M', 'M', 'M', 'm', 'M'],
  },
  'Minor Pentatonic': {
    'scaleStepsRoman': ['I', '♭III', 'IV', 'V', '♭VII'],
    'intervals': [0, 3, 5, 7, 10],
    'scaleDegrees': [
      Interval.P1,
      null,
      null,
      Interval.m3,
      null,
      Interval.P4,
      null,
      Interval.P5,
      null,
      null,
      Interval.m7,
      null,
    ],
    'function': ['I', '♭III', 'IV', 'V', '♭VII'],
    'chordType': ['m', 'M', 'M', 'm', 'm'],
  },
  'Blues': {
    'scaleStepsRoman': ['I', '♭III', 'IV', '♭V', 'V', '♭VII'],
    'intervals': [0, 3, 5, 6, 7, 10],
    'scaleDegrees': [
      Interval.P1,
      null,
      null,
      Interval.m3,
      null,
      Interval.P4,
      Interval.d5,
      Interval.P5,
      null,
      null,
      Interval.m7,
      null,
    ],
    'function': ['I', '♭III', 'IV', '♭V', 'V', '♭VII'],
    'chordType': ['m', 'M', '7', 'm', '7', 'm'],
  },
  'Major Blues': {
    'scaleStepsRoman': ['I', 'II', '♭III', 'III', 'IV', 'V', '♭VII'],
    'intervals': [0, 2, 3, 4, 5, 7, 10],
    'scaleDegrees': [
      Interval.P1,
      null,
      Interval.M2,
      Interval.m3,
      Interval.M3,
      Interval.P4,
      null,
      Interval.P5,
      null,
      null,
      Interval.m7,
      null,
    ],
    'function': ['I', 'II', '♭III', 'III', 'IV', 'V', '♭VII'],
    'chordType': ['M', 'M', 'm', 'M', '7', '7', 'm'],
  },
  'Minor Blues': {
    'scaleStepsRoman': ['I', '♭III', 'IV', '♭V', 'V', '♭VII'],
    'intervals': [0, 3, 5, 6, 7, 10],
    'scaleDegrees': [
      Interval.P1,
      null,
      null,
      Interval.m3,
      null,
      Interval.P4,
      Interval.d5,
      Interval.P5,
      null,
      null,
      Interval.m7,
      null,
    ],
    'function': ['I', '♭III', 'IV', '♭V', 'V', '♭VII'],
    'chordType': ['m', 'M', '7', 'm', '7', 'm'],
  },
  'Egyptian': {
    'scaleStepsRoman': ['I', 'II', 'IV', 'V', 'VII'],
    'intervals': [0, 2, 5, 7, 10],
    'scaleDegrees': [
      Interval.P1,
      null,
      Interval.M2,
      null,
      null,
      Interval.P4,
      null,
      Interval.P5,
      null,
      null,
      null,
      Interval.M7,
    ],
    'function': ['I', 'II', 'IV', 'V', 'VII'],
    'chordType': ['M', 'M', 'M', 'm', 'M'],
  },
  'Hirajoshi': {
    'scaleStepsRoman': ['I', '♭II', '♭III', 'V', '♭VI'],
    'intervals': [0, 1, 3, 7, 8],
    'scaleDegrees': [
      Interval.P1,
      Interval.m2,
      null,
      Interval.m3,
      null,
      null,
      Interval.P5,
      Interval.m6,
      null,
      null,
      null,
    ],
    'function': ['I', '♭II', '♭III', 'V', '♭VI'],
    'chordType': ['°', 'm', '°', 'm', '°'],
  },
  'In-Sen': {
    'scaleStepsRoman': ['I', '♭II', 'IV', 'V', 'VII'],
    'intervals': [0, 1, 5, 7, 10],
    'scaleDegrees': [
      Interval.P1,
      Interval.m2,
      null,
      null,
      null,
      Interval.P4,
      null,
      Interval.P5,
      null,
      null,
      null,
      Interval.M7,
    ],
    'function': ['I', '♭II', 'IV', 'V', 'VII'],
    'chordType': ['°', 'm', 'M', 'M', '°'],
  },
  'Iwato': {
    'scaleStepsRoman': ['I', '♭II', 'IV', 'V', '♭VII'],
    'intervals': [0, 1, 5, 7, 10],
    'scaleDegrees': [
      Interval.P1,
      Interval.m2,
      null,
      null,
      null,
      Interval.P4,
      null,
      Interval.P5,
      null,
      null,
      Interval.m7,
      null,
    ],
    'function': ['I', '♭II', 'IV', 'V', '♭VII'],
    'chordType': ['°', 'm', '°', 'm', '°'],
  },
  'Kumoi': {
    'scaleStepsRoman': ['I', 'II', 'IV', 'V', 'VI'],
    'intervals': [0, 2, 5, 7, 9],
    'scaleDegrees': [
      Interval.P1,
      null,
      Interval.M2,
      null,
      null,
      Interval.P4,
      null,
      Interval.P5,
      null,
      Interval.M6,
      null,
      null,
    ],
    'function': ['I', 'II', 'IV', 'V', 'VI'],
    'chordType': ['M', 'm', 'M', 'm', 'M'],
  },
  'Pelog': {
    'scaleStepsRoman': ['I', 'II', '♭III', 'V', '♭VI'],
    'intervals': [0, 2, 3, 7, 8],
    'scaleDegrees': [
      Interval.P1,
      null,
      Interval.M2,
      Interval.m3,
      null,
      null,
      null,
      Interval.P5,
      Interval.m6,
      null,
      null,
      null,
    ],
    'function': ['I', 'II', '♭III', 'V', '♭VI'],
    'chordType': ['M', 'm', 'm', 'M', 'm'],
  },
  'Prometheus': {
    'scaleStepsRoman': ['I', 'II', 'IV', 'V', 'VII'],
    'intervals': [0, 2, 5, 7, 11],
    'scaleDegrees': [
      Interval.P1,
      null,
      Interval.M2,
      null,
      null,
      Interval.P4,
      null,
      Interval.P5,
      null,
      null,
      null,
      Interval.M7,
    ],
    'function': ['I', 'II', 'IV', 'V', 'VII'],
    'chordType': ['M', 'm', 'M', 'M', 'M'],
  },
  'Prometheus Neapolitan': {
    'scaleStepsRoman': ['I', '♭II', 'IV', 'V', 'VII'],
    'intervals': [0, 1, 5, 7, 11],
    'scaleDegrees': [
      Interval.P1,
      Interval.m2,
      null,
      null,
      null,
      Interval.P4,
      null,
      Interval.P5,
      null,
      null,
      null,
      Interval.M7,
    ],
    'function': ['I', '♭II', 'IV', 'V', 'VII'],
    'chordType': ['°', 'm', 'M', 'M', 'M'],
  },
  'Prometheus Spanish': {
    'scaleStepsRoman': ['I', 'II', '♭III', 'V', 'VII'],
    'intervals': [0, 2, 3, 7, 11],
    'scaleDegrees': [
      Interval.P1,
      null,
      Interval.M2,
      Interval.m3,
      null,
      null,
      null,
      Interval.P5,
      null,
      null,
      null,
      Interval.M7,
    ],
    'function': ['I', 'II', '♭III', 'V', 'VII'],
    'chordType': ['M', 'm', 'm', 'M', 'M'],
  },
  'Ritusen': {
    'scaleStepsRoman': ['I', '♭II', '♭III', 'V', '♭VI'],
    'intervals': [0, 1, 3, 7, 8],
    'scaleDegrees': [
      Interval.P1,
      Interval.m2,
      null,
      Interval.m3,
      null,
      null,
      null,
      Interval.P5,
      Interval.m6,
      null,
      null,
      null,
    ],
    'function': ['I', '♭II', '♭III', 'V', '♭VI'],
    'chordType': ['°', 'm', '°', 'm', '°'],
  },
  'Ryukyu': {
    'scaleStepsRoman': ['I', '♭II', 'IV', 'V', '♭VII'],
    'intervals': [0, 1, 5, 7, 10],
    'scaleDegrees': [
      Interval.P1,
      Interval.m2,
      null,
      null,
      null,
      Interval.P4,
      null,
      Interval.P5,
      null,
      null,
      Interval.m7,
      null,
    ],
    'function': ['I', '♭II', 'IV', 'V', '♭VII'],
    'chordType': ['°', 'm', 'M', 'M', 'm'],
  },
  'Yo': {
    'scaleStepsRoman': ['I', 'II', 'IV', 'V', '♭VII'],
    'intervals': [0, 2, 5, 7, 10],
    'scaleDegrees': [
      Interval.P1,
      null,
      Interval.M2,
      null,
      null,
      Interval.P4,
      null,
      Interval.P5,
      null,
      null,
      Interval.m7,
      null,
    ],
    'function': ['I', 'II', 'IV', 'V', '♭VII'],
    'chordType': ['M', 'm', 'M', 'm', '°'],
  },
  'Yo-Kumoi': {
    'scaleStepsRoman': ['I', 'II', 'III', 'V', '♭VII'],
    'intervals': [0, 2, 4, 7, 10],
    'scaleDegrees': [
      Interval.P1,
      null,
      Interval.M2,
      null,
      Interval.M3,
      null,
      null,
      Interval.P5,
      null,
      null,
      Interval.m7,
      null,
    ],
    'function': ['I', 'II', 'III', 'V', '♭VII'],
    'chordType': ['M', 'M', 'm', 'm', '°'],
  },
  'Zhi': {
    'scaleStepsRoman': ['I', 'II', 'IV', 'V', '♭VII'],
    'intervals': [0, 2, 5, 7, 10],
    'scaleDegrees': [
      Interval.P1,
      null,
      Interval.M2,
      null,
      null,
      Interval.P4,
      null,
      Interval.P5,
      null,
      null,
      Interval.m7,
      null,
    ],
    'function': ['I', 'II', 'IV', 'V', '♭VII'],
    'chordType': ['M', 'm', 'M', 'm', '°'],
  },
  'Zhi-Yu': {
    'scaleStepsRoman': ['I', 'II', 'III', 'V', '♭VII'],
    'intervals': [0, 2, 4, 7, 10],
    'scaleDegrees': [
      Interval.P1,
      null,
      Interval.M2,
      null,
      Interval.M3,
      null,
      null,
      Interval.P5,
      null,
      null,
      Interval.m7,
      null,
    ],
    'function': ['I', 'II', 'III', 'V', '♭VII'],
    'chordType': ['M', 'M', 'm', 'm', '°'],
  },
  'Zhi-Yu-Kumoi': {
    'scaleStepsRoman': ['I', 'II', 'III', 'V', '♭VII'],
    'intervals': [0, 2, 4, 7, 9],
    'scaleDegrees': [
      Interval.P1,
      null,
      Interval.M2,
      null,
      Interval.M3,
      null,
      null,
      Interval.P5,
      null,
      null,
      Interval.m7,
      null,
    ],
    'function': ['I', 'II', 'III', 'V', '♭VII'],
    'chordType': ['M', 'M', 'm', 'm', '°'],
  },
};
